# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x65\x64\x65rated_service.proto\x12\x0esctl_federated\"!\n\x0cModelRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\":\n\x0cModelWeights\x12\x14\n\x0cround_number\x18\x01 \x01(\x05\x12\x14\n\x0cweights_data\x18\x02 \x01(\x0c\"x\n\x0bModelUpdate\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x14\n\x0cweights_data\x18\x03 \x01(\x0c\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\x12\x15\n\ranomaly_score\x18\x05 \x01(\x02\"3\n\x0f\x41\x63knowledgement\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\x04Ping\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x16\n\x04Pong\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf3\x01\n\x11\x46\x65\x64\x65ratedLearning\x12N\n\x0eGetGlobalModel\x12\x1c.sctl_federated.ModelRequest\x1a\x1c.sctl_federated.ModelWeights\"\x00\x12Q\n\x0fSendModelUpdate\x12\x1b.sctl_federated.ModelUpdate\x1a\x1f.sctl_federated.Acknowledgement\"\x00\x12;\n\x0bHealthCheck\x12\x14.sctl_federated.Ping\x1a\x14.sctl_federated.Pong\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELREQUEST']._serialized_start=43
  _globals['_MODELREQUEST']._serialized_end=76
  _globals['_MODELWEIGHTS']._serialized_start=78
  _globals['_MODELWEIGHTS']._serialized_end=136
  _globals['_MODELUPDATE']._serialized_start=138
  _globals['_MODELUPDATE']._serialized_end=258
  _globals['_ACKNOWLEDGEMENT']._serialized_start=260
  _globals['_ACKNOWLEDGEMENT']._serialized_end=311
  _globals['_PING']._serialized_start=313
  _globals['_PING']._serialized_end=338
  _globals['_PONG']._serialized_start=340
  _globals['_PONG']._serialized_end=362
  _globals['_FEDERATEDLEARNING']._serialized_start=365
  _globals['_FEDERATEDLEARNING']._serialized_end=608
# @@protoc_insertion_point(module_scope)
