# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_service_pb2 as federated__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningStub(object):
    """The FederatedLearning service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalModel = channel.unary_unary(
                '/sctl_federated.FederatedLearning/GetGlobalModel',
                request_serializer=federated__service__pb2.ModelRequest.SerializeToString,
                response_deserializer=federated__service__pb2.ModelWeights.FromString,
                _registered_method=True)
        self.SendModelUpdate = channel.unary_unary(
                '/sctl_federated.FederatedLearning/SendModelUpdate',
                request_serializer=federated__service__pb2.ModelUpdate.SerializeToString,
                response_deserializer=federated__service__pb2.Acknowledgement.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sctl_federated.FederatedLearning/HealthCheck',
                request_serializer=federated__service__pb2.Ping.SerializeToString,
                response_deserializer=federated__service__pb2.Pong.FromString,
                _registered_method=True)


class FederatedLearningServicer(object):
    """The FederatedLearning service definition.
    """

    def GetGlobalModel(self, request, context):
        """1. Edge Worker calls this to get the current global model weights (W_t)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelUpdate(self, request, context):
        """2. Edge Worker calls this to send its locally trained weights (W_t^k) back to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """3. Optional: Heartbeat to ensure Zero-Trust connection is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__service__pb2.ModelRequest.FromString,
                    response_serializer=federated__service__pb2.ModelWeights.SerializeToString,
            ),
            'SendModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelUpdate,
                    request_deserializer=federated__service__pb2.ModelUpdate.FromString,
                    response_serializer=federated__service__pb2.Acknowledgement.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=federated__service__pb2.Ping.FromString,
                    response_serializer=federated__service__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sctl_federated.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sctl_federated.FederatedLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """The FederatedLearning service definition.
    """

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sctl_federated.FederatedLearning/GetGlobalModel',
            federated__service__pb2.ModelRequest.SerializeToString,
            federated__service__pb2.ModelWeights.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sctl_federated.FederatedLearning/SendModelUpdate',
            federated__service__pb2.ModelUpdate.SerializeToString,
            federated__service__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sctl_federated.FederatedLearning/HealthCheck',
            federated__service__pb2.Ping.SerializeToString,
            federated__service__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
